version: 2
updates:
  - package-ecosystem: pub
    directories:
      - "**/*"
    schedule:
      interval: weekly
    groups:
      pub:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directories: 
      - /
      - .github/actions/additional-checks
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]